pointcuts:
  - 1
  - 2
#      - 'ru.erminson.lc.repository'
#      - 'ru.erminson.lc.service'

topic:
  title: TopicTitle2
  duration: 2
#pointcuts:
#  ru.erminson.lc.repository,
#  ru.erminson.lc.service
