server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}