server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erminson/configproperties.git
          skipSslValidation: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}