//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.16 at 06:22:40 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.erminson.ru/ps/soap/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.erminson.lc.soap.model;
