spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_URL}       #lc-postgres:5432/lc-db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  application:
    name: learning-center-service

logging:
  enabled: true
  packages:
    - ru.erminson.lc.bean_post_processor
    - ru.erminson.lc.repository
    - ru.erminson.lc.service

soap:
  payment-url: ${PAYMENT_URL}

topic:
  title: TopicTitle2
  duration: 2

db:
  type: jdbc  #  yaml