spring:
  application:
    name: learning-center-service
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

logging:
  level:
    org.springframework.cloud.sleuth.log: TRACE