server:
  port: 8081

spring:
  application:
    name: learning-center-service
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

logging:
  enabled: true
  packages:
    - ru.erminson.lc.bean_post_processor
    - ru.erminson.lc.repository
    - ru.erminson.lc.service

soap:
  payment-url: ${PAYMENT_URL}

topic:
  title: TopicTitle2
  duration: 2

db:
  type: jdbc  #  yaml