spring:
  sql:
    init:
      schema-locations: sql/schema.sql
      data-locations: sql/data.sql
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:lc
    username: admin
    password: admin


logging:
  enabled: true
  packages:
    - ru.erminson.lc.bean_post_processor
#    - ru.erminson.lc.repository
#    - ru.erminson.lc.service
topic:
  title: TopicTitle2
  duration: 2